sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r dev-requirements.txt
  - pip install -r requirements.txt
script:
  - pydocstyle game_of_graphql/
  - isort --check-only --verbose --recursive game_of_graphql/
  - pylint game_of_graphql/
  - bandit -r game_of_graphql/
